# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - BudgetTracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore
        run: dotnet restore

      - name: Build project
        run: dotnet build -c Release --no-restore
        
      - name: Publish dotnet
        run: dotnet publish BudgetTracker.csproj -c Release -o publish

      - name: Verify (DEBUG)
        run: ls -R publish
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BudgetTracker'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE_PROD }}
          slot-name: 'Production'
          package: .
          
